module.exports = {
  singleQuote: true,
  semi: true,
  tabWidth: 2,
  useTabs: true,
  trailingComma: 'all',
  jsxBracketSameLine: false,
  arrowParens: 'avoid',
  jsxSelfClosing: true,
  spaceBeforeFunctionParen: false,
  spaceBeforeBlockStatements: true,
  spaceBeforeControlStatements: true,
  spaceInfixOps: true,
  bracketSpacing: true,
  jsxSingleQuote: true,
  plugins: ['prettier-plugin-tailwindcss'],
};